name: OWASP Scan
on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install OWASP ZAP
        uses: owasp/zap-action@v1
      - name: Scan Website
        run: zap-cli scan -f scan.yaml
      - name: Generate Report
        run: zap-cli report -o report.html
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.html
